name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm run build

    - name: Copy DragDropInteractions
      shell: /bin/bash -e {0}
      run: |
        cp -vr "vendor/github.com/codrops/DragDropInteractions" "build/"

    - name: Copy Ventus
      shell: /bin/bash -e {0}
      run: |
        mkdir -p ./build/Ventus
        cp -vr "./vendor/github.com/rlamana/Ventus/dist" "./build/Ventus/"
        cp -vr "./vendor/github.com/rlamana/Ventus/examples" "./build/Ventus/"
        mv ./build/index.html ./build/covalent.html

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
